---
language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

notifications:
  email:
  - paddygarmin@gmail.com
  slack:
    rooms:
      - undeadbaby:WDGNd6FP2Uu61jNcbMaHLSIv#random
      on_success: change
      on_failure: always
travis encrypt "undeadbaby:WDGNd6FP2Uu61jNcbMaHLSIv" --add notifications.slack

script: make
