---
language: c
before_install:
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq gcc-avr binutils-avr avr-libc

notifications:
  slack:
    rooms:
    - undeadbaby:$SLACK_KEY
    - undeadbaby:$Slack_key_temp
    on_success: always
    on_failure: always


script: make
